define([], function () {
  return {
    AppTitle: 'User Provisioning Center',
    AppDescription: 'Onboard, manage and offboard Microsoft 365 users.',
    TabDashboard: 'Dashboard',
    TabNewUser: 'New user',
    LoadingLabel: 'Loading',
    EmptyGenericTitle: 'Nothing here yet',
    EmptyGenericBody: 'Items will appear here once they exist.',
    ErrorGenericTitle: 'Something went wrong',
    CorrelationIdLabel: 'Correlation ID',
    RetryLabel: 'Retry',
    RefreshLabel: 'Refresh',
    CloseLabel: 'Close',

    TabDraftBadge: 'Draft',
    StartOverLabel: 'Start over',
    DiscardDraftTitle: 'Discard this draft?',
    DiscardDraftBody: 'All information entered for this user will be removed.',
    DiscardDraftConfirm: 'Discard draft',
    KeepEditingLabel: 'Keep editing',

    PreflightMissingTitle: 'Some capabilities are unavailable to you',
    PreflightMissingIntro:
      'Your account is missing Entra roles required for these operations. The app cannot grant them; ask a Privileged Role Administrator.',
    PreflightErrorTitle: 'Permission preflight failed',

    WizardTitle: 'Onboard a new user',
    WizardStepPersonal: 'Personal',
    WizardStepEmployment: 'Employment',
    WizardStepIdentity: 'Identity',
    WizardStepAccount: 'Account settings',
    WizardStepLicenses: 'Licenses',
    WizardStepAccess: 'Access',
    WizardStepReview: 'Review & submit',
    WizardStepDescPersonal: 'Basic information about the person joining the organization.',
    WizardStepDescEmployment: 'Role, department and reporting line.',
    WizardStepDescIdentity: 'Pick the sign-in name. Availability is checked against the directory, including recently deleted users.',
    WizardStepDescAccount: 'Regional settings and how first sign-in credentials are handed over.',
    WizardStepDescLicenses: 'Availability reflects your tenant subscriptions; costs come from the license cost table.',
    WizardStepDescAccess: 'Groups, Teams, SharePoint sites and applications to grant, and when to schedule an access review.',
    WizardStepDescReview: 'Nothing is created yet — submitting sends the request for approval.',

    AccessSecurityGroupsLabel: 'Security groups',
    AccessSecurityGroupsHint: 'Search Entra security groups by name.',
    AccessM365GroupsLabel: 'Microsoft 365 groups',
    AccessM365GroupsHint: 'Search Entra Microsoft 365 groups by name.',
    AccessTeamsLabel: 'Teams',
    AccessTeamsHint: 'Search the curated Teams catalog by name.',
    AccessSitesLabel: 'SharePoint sites',
    AccessSitesHint: 'Search the curated SharePoint site catalog by name.',
    AccessApplicationsLabel: 'Applications',
    AccessApplicationsHint: 'Search the curated application catalog by name.',
    AccessGroupSearchPlaceholder: 'Search by name…',
    AccessGroupSearchHint: 'Type at least 2 characters to search.',
    AccessGroupSearchNoMatches: 'No groups found.',
    AccessCatalogNoMatches: 'No matches.',
    AccessRoleMember: 'Member',
    AccessRoleOwner: 'Owner',
    AccessRoleVisitor: 'Visitor',
    AccessExpirationLabel: 'Review access after (days)',
    AccessExpirationHint:
      'Leave at 0 for no scheduled review. A service-desk task is created to review this account’s access after this many days — nothing happens automatically.',
    AccessNoCatalogItems: 'None configured. Ask an admin to add entries to the catalog list.',
    AccessExpirationNone: 'No review scheduled',
    ApproverGroupIdLabel: 'Approver group (optional)',
    ApproverGroupIdHint:
      'Entra security group object ID. When set, only members of this group can approve jobs created from this template — leave blank for no additional restriction.',
    ApprovalRestrictedMessage: 'This job can only be approved by a member of the group this template requires.',
    ApprovalRestrictedNotMember: 'You are not a member of the required approver group, so you cannot approve this job.',

    IdentityAccountTypeLabel: 'Account type',
    IdentityAccountTypeMember: 'Employee or contractor (creates an account)',
    IdentityAccountTypeGuest: 'External guest (sends an invitation)',
    IdentityGuestEmailLabel: 'Guest email address',
    IdentityGuestIntro: 'Entra emails an invitation to this address — there is no password or sign-in name to choose.',
    CloneFromLabel: 'Clone access from (optional)',
    CloneFromHint: 'Copies this person’s licenses and eligible group memberships onto the new hire, in addition to anything selected below.',
    WizardStepsAriaLabel: 'Wizard steps',
    WizardStepCompletedAria: 'completed',
    WizardStepHasErrorsAria: 'needs attention',
    WizardStepOfLabel: 'Step {0} of {1}',
    BackLabel: 'Back',
    NextLabel: 'Next',
    SubmitLabel: 'Submit for approval',
    SubmitNoApprovalLabel: 'Create job',
    SubmittingLabel: 'Submitting…',
    SubmitSuccess: 'Provisioning request submitted and pending approval.',
    SubmitSuccessNoApproval: 'Provisioning job created and ready to run.',
    SubmitFailure: 'The request could not be submitted.',
    WizardStepDescReviewNoApproval:
      'Nothing is created yet — submitting creates a job that is ready to run.',
    ReviewIntroNoApproval:
      'Review the request. Submitting creates a provisioning job that can be run from the dashboard.',
    OffboardStepDescReviewNoApproval:
      'Nothing is executed yet — submitting creates a job that is ready to run.',
    OffboardSubmitSuccessNoApproval: 'Offboarding job created and ready to run.',
    BulkIntroNoApproval:
      'Upload a CSV file to create multiple onboarding jobs at once. Each row becomes its own job, ready to run from the dashboard.',

    FirstNameLabel: 'First name',
    LastNameLabel: 'Last name',
    DisplayNameLabel: 'Display name',
    EmployeeIdLabel: 'Employee ID',
    MobilePhoneLabel: 'Mobile phone',
    PersonalEmailLabel: 'Personal email',
    PhotoLabel: 'Photo',
    PhotoHint: 'Optional. Resized and compressed automatically — large photos are shrunk to fit.',
    ChoosePhotoLabel: 'Choose photo',
    ChangePhotoLabel: 'Change photo',
    RemovePhotoLabel: 'Remove photo',
    PhotoUploadError: 'That image could not be used — try a smaller or simpler photo.',
    JobTitleLabel: 'Job title',
    DepartmentLabel: 'Department',
    CompanyLabel: 'Company',
    OfficeLabel: 'Office location',
    CountryLabel: 'Country',
    CountryHint: 'The physical/office country. Separate from usage location, which drives license eligibility.',
    ManagerLabel: 'Manager',
    ManagerSearchPlaceholder: 'Search by name or email',
    EmployeeTypeLabel: 'Employee type',
    EmployeeTypeEmployee: 'Employee',
    EmployeeTypeContractor: 'Contractor',
    HireDateLabel: 'Hire date',
    DomainLabel: 'Domain',
    UpnLabel: 'User principal name',
    MailNicknameLabel: 'Mail nickname',
    UsageLocationLabel: 'Usage location',
    AccountEnabledLabel: 'Account enabled at creation',
    CredentialModeLabel: 'First sign-in credential',
    CredentialModePassword: 'Temporary password',
    CredentialModeTap: 'Temporary Access Pass (TAP)',
    ForceChangePasswordLabel: 'Require password change at first sign-in',

    ValidationRequired: 'This field is required.',
    ValidationTooLong: 'This value is too long.',
    ValidationInvalidEmail: 'Enter a valid email address.',
    ValidationInvalidPhone: 'Enter a valid phone number.',
    ValidationInvalidDate: 'Enter a valid date.',
    ValidationInvalidCountry: 'Select a country.',
    ValidationInvalidChoice: 'Select a valid option.',
    ValidationInvalidUpn: 'Enter a valid user principal name.',
    ValidationInvalidLocalPart: 'Only a-z, 0-9, dots and hyphens; no leading or trailing dot.',
    EmployeeIdDuplicate: 'This employee ID already exists in the directory.',
    EmployeeIdChecking: 'Checking employee ID…',

    IdentityCandidatesLabel: 'Available sign-in names',
    IdentityRecommended: 'Recommended',
    IdentityAlternatives: 'Alternatives',
    IdentityRejectedTitle: 'Not available',
    IdentityReasonReserved: 'reserved name',
    IdentityReasonCollision: 'already in use',
    IdentityReasonCollisionDeleted: 'used by a recently deleted user',
    IdentityNoCandidate: 'No available name could be generated. Adjust the name fields.',
    IdentityResolving: 'Checking name availability…',
    IdentityNeedsNames: 'Enter first and last name in step 1 to generate sign-in names.',

    LicenseColumnProduct: 'Product',
    LicenseColumnAvailable: 'Available',
    LicenseColumnCost: 'Cost / month',
    LicenseExhausted: 'No units left',
    LicenseNoCost: '—',
    LicenseTotalPerMonth: 'Selected licenses per month',

    ReviewIntro: 'Review the request. Submitting creates a provisioning job that requires approval before anything is executed.',
    ReviewNoLicenses: 'No licenses selected',
    ReviewNoManager: 'No manager selected',
    ReviewNoCountry: 'Not set',
    ReviewApproverGroupDefault: 'Standard approval (no template restriction)',
    ReviewPhotoAttached: 'Attached',
    ReviewPhotoNone: 'None',
    ReviewEditLabel: 'Edit',
    ReviewEditSectionAria: 'Edit {0}',
    ReviewValidationTitle: 'Some information is missing or invalid',

    JobsTitle: 'Provisioning jobs',
    JobsEmptyTitle: 'No provisioning jobs',
    JobsEmptyBody: 'Submitted onboarding requests will appear here.',
    JobsEmptyCta: 'Create your first user',
    JobColumnJob: 'Job',
    JobColumnCreated: 'Created',
    JobColumnActions: 'Actions',
    ApprovedByLabel: 'Approved by',
    JobColumnType: 'Type',
    JobColumnTarget: 'Target user',
    JobColumnStatus: 'Status',
    JobColumnRequestedBy: 'Requested by',
    JobDetailTitle: 'Job details',
    JobStepsTitle: 'Steps',
    ApproveLabel: 'Approve',
    RunLabel: 'Run now',
    ResumeLabel: 'Resume',
    RetryStepLabel: 'Retry step',
    SkipStepLabel: 'Skip step',
    CancelJobLabel: 'Cancel job',
    CancelJobDialogTitle: 'Cancel this job?',
    CancelJobDialogBody:
      'Steps that have already completed will not be rolled back. This cannot be undone.',
    KeepJobLabel: 'Keep job',
    RegenerateCredentialsLabel: 'Regenerate credentials',
    JobRunningLabel: 'Running…',
    JobAttemptsLabel: 'attempts',
    JobStatusAnnouncement: 'Job status: {0}',
    JobApprovedToast: 'Job approved.',
    JobCancelledToast: 'Job cancelled.',
    JobActionFailed: 'The action failed.',
    JobProgressLabel: 'Step {0} of {1}',
    JobDoNotClose: 'Provisioning is in progress — keep this tab open. Closing it pauses the job; it resumes when you reopen the drawer.',
    JobCompletedOf: 'Completed {0} of {1} steps',
    JobElapsedLabel: 'Elapsed',
    JobStepStarting: 'Starting…',
    StatusPendingApproval: 'Pending approval',
    StatusApproved: 'Approved',
    StatusScheduled: 'Scheduled',
    StatusRunning: 'Running',
    StatusPartiallyFailed: 'Partially failed',
    StatusFailed: 'Failed',
    StatusCompleted: 'Completed',
    StatusCancelled: 'Cancelled',
    StepStatusPending: 'Pending',
    StepStatusRunning: 'Running',
    StepStatusCompleted: 'Completed',
    StepStatusFailed: 'Failed',
    StepStatusSkipped: 'Skipped',

    StepValidateInput: 'Validate input',
    StepCreateUser: 'Create user',
    StepSetUsageLocation: 'Set usage location',
    StepAssignManager: 'Assign manager',
    StepAssignLicenses: 'Assign licenses',
    StepPresentCredentials: 'Hand over credentials',
    StepFinalizeAudit: 'Finalize audit',

    JobTypeOnboard: 'Onboard',
    JobTypeOffboard: 'Offboard',
    JobTypeTransfer: 'Transfer',
    JobTypeClone: 'Clone',
    JobTypeBulk: 'Bulk',

    KpiFailed7: 'Failed (7 days)',
    KpiCompleted7: 'Completed (7 days)',
    SearchJobsPlaceholder: 'Search by user or requester',
    FilterTypeAll: 'All types',
    JobsNoMatches: 'No jobs match the current filters.',

    TabTemplates: 'Templates',
    TemplatesTitle: 'Provisioning templates',
    TemplatesEmptyTitle: 'No templates yet',
    TemplatesEmptyBody: 'Templates pre-fill the onboarding wizard with department defaults.',
    NewTemplateLabel: 'New template',
    TemplateNameLabel: 'Template name',
    TemplateColumnName: 'Name',
    TemplateColumnActive: 'Active',
    TemplateColumnVersion: 'Version',
    TemplateInactiveLabel: 'Inactive',
    TemplateActiveLabel: 'Active (selectable in the wizard)',
    TemplateSavedToast: 'Template saved.',
    TemplateEditTitle: 'Edit template',
    SaveLabel: 'Save',
    CancelLabel: 'Cancel',
    StartFromTemplateLabel: 'Start from template',
    StartFromBlank: 'Blank',
    TemplateAppliedToast: 'Template applied: {0}',

    TabOffboard: 'Offboard user',
    OffboardTitle: 'Offboard a user',
    OffboardStepTarget: 'Select user',
    OffboardStepAccess: 'Access removal',
    OffboardStepTiming: 'Timing',
    OffboardStepDescTarget: 'Search the directory for the person leaving the organization.',
    OffboardStepDescAccess:
      'Choose what is removed. Sign-in is always blocked and sessions revoked.',
    OffboardStepDescTiming: 'Run immediately after approval, or on a chosen date.',
    OffboardStepDescReview: 'Nothing is executed yet — submitting sends the request for approval.',
    OffboardUserLabel: 'User',
    OffboardAlwaysBlock:
      'Sign-in is blocked and all active sessions are revoked as the first step of every offboarding.',
    OffboardRemoveLicensesLabel: 'Remove assigned licenses',
    OffboardRemoveGroupsLabel: 'Remove group memberships',
    OffboardMailboxLabel: 'Mailbox',
    OffboardMailboxNone: 'Leave unchanged',
    OffboardMailboxShared: 'Convert to shared mailbox (service desk task)',
    OffboardMailboxForward: 'Forward mail (service desk task)',
    OffboardForwardAddressLabel: 'Forwarding address',
    OffboardOneDriveLabel: 'Grant OneDrive access to (optional)',
    OffboardTimingImmediate: 'As soon as the job is approved and run',
    OffboardTimingScheduled: 'On a date',
    OffboardDateLabel: 'Date',
    OffboardSubmitSuccess: 'Offboarding request submitted and pending approval.',
    ScheduledForLabel: 'Scheduled for',
    YesLabel: 'Yes',
    NoLabel: 'No',
    StepValidateTarget: 'Validate target user',
    StepBlockSignIn: 'Block sign-in & revoke sessions',
    StepRemoveLicenses: 'Remove licenses',
    StepRemoveGroups: 'Remove group memberships',
    StepCreateHandoverTasks: 'Create hand-over tasks',

    TabTransfer: 'Transfer',
    TransferTitle: 'Transfer user',
    TransferIntro:
      'Change department, job title, office, manager, or licenses for an existing user. Leave a field blank to leave it unchanged.',
    TransferUserLabel: 'User to transfer',
    TransferLeaveBlankHint: 'Leave blank for no change',
    TransferAddLicensesLabel: 'Add licenses',
    TransferRemoveLicensesLabel: 'Remove licenses',
    TransferNoCurrentLicenses: 'This user has no assigned licenses.',

    TabBulk: 'Bulk import',
    BulkTitle: 'Bulk user import',
    BulkIntro:
      'Upload a CSV file to create multiple onboarding requests at once. Each row becomes its own job in the approval pipeline.',
    BulkDownloadTemplate: 'Download CSV template',
    BulkChooseFile: 'Choose CSV file',
    BulkValidateLabel: 'Validate rows',
    BulkValidatingLabel: 'Validating row {0} of {1}…',
    BulkReadySummary: '{0} of {1} rows are ready.',
    BulkSubmitLabel: 'Create {0} jobs',
    BulkSubmittedToast: '{0} onboarding requests created.',
    BulkTooManyRows: 'A maximum of {0} rows can be imported at once.',
    BulkNoDataRows: 'The file has no data rows.',
    BulkMissingColumns: 'Missing required columns: {0}',
    BulkColumnRow: 'Row',
    BulkColumnProblems: 'Problems',
    BulkRowReady: 'Ready',
    BulkRowError: 'Error',
    BulkErrDuplicateInFile: 'Duplicate employee ID in the file',
    BulkErrUnknownLicense: 'Unknown license: {0}',
    BulkErrUnknownDomain: 'Domain is not verified in this tenant',
    BulkErrNoUpn: 'No available sign-in name could be generated',
    BulkErrDuplicateUpn: 'Sign-in name collides with another row',
    BulkErrUnknownTemplate: 'Unknown template: {0}',

    TabBulkOffboard: 'Bulk offboard',
    BulkOffboardTitle: 'Bulk user offboarding',
    BulkOffboardIntro:
      'Upload a CSV file to create multiple offboarding requests at once. Each row becomes its own job in the approval pipeline.',
    BulkOffboardIntroNoApproval:
      'Upload a CSV file to create multiple offboarding requests at once. Each row becomes its own job, ready to run.',
    BulkOffboardSubmitLabel: 'Create {0} jobs',
    BulkOffboardSubmittedToast: '{0} offboarding requests created.',
    BulkErrInvalidMailboxAction: 'Unknown mailboxAction: {0} (use none, convertShared, or forward)',
    BulkErrUserNotFound: 'No user found in the directory with this sign-in name',
    OffboardForwardingRequired: 'A forwarding address is required when mailboxAction is forward',

    TabTasks: 'Tasks',
    TasksTitle: 'Service desk tasks',
    TasksEmptyTitle: 'No open tasks',
    TasksEmptyBody: 'Hand-over work that cannot be automated lands here.',
    ShowCompletedLabel: 'Show completed',
    MarkDoneLabel: 'Mark done',
    TaskCompletedToast: 'Task completed.',
    TaskStatusOpen: 'Open',
    TaskStatusDone: 'Done',
    TaskCompletedByLabel: 'Completed by',
    TasksColumnTitle: 'Title',
    TasksColumnType: 'Type',
    TasksColumnInstructions: 'Instructions',
    TasksColumnAssignedTo: 'Assigned to',
    ExportCsvLabel: 'Export CSV',
    TaskTypeMailboxConvertShared: 'Convert mailbox to shared',
    TaskTypeMailboxDelegation: 'Mailbox delegation',
    TaskTypeMailForwarding: 'Mail forwarding',
    TaskTypeHideFromGal: 'Hide from address list',
    TaskTypeDistributionList: 'Distribution lists',
    TaskTypeLitigationHold: 'Litigation hold',
    TaskTypeOneDriveHandling: 'OneDrive handling',
    TaskTypeAutoReply: 'Automatic replies',
    TaskTypeHardware: 'Hardware',
    TaskTypeThirdPartyApp: 'Third-party app',
    TaskTypeOnPremAdAccount: 'On-premises AD account action',
    TaskTypeGroupAssignment: 'Group assignment',
    TaskTypeTeamAssignment: 'Teams assignment',
    TaskTypeSharePointAccess: 'SharePoint site access',
    TaskTypeApplicationAssignment: 'Application assignment',
    TaskTypeAccessReview: 'Access review',
    TaskTypeOther: 'Other',

    TabSettings: 'Settings',
    SettingsTitle: 'Settings',
    SettingsIntro:
      'These settings are stored on this site and apply to everyone using the Provisioning Center.',
    SettingsRequireApprovalLabel: 'Require approval before jobs can run',
    SettingsRequireApprovalHint:
      'Off: new requests are created ready to run. Jobs already pending approval keep their current state.',
    SettingsBulkLimitLabel: 'Bulk import row limit',
    SettingsRefreshLabel: 'Dashboard refresh interval (seconds)',
    SettingsSavedToast: 'Settings saved.',
    SettingsSaveFailed: 'The settings could not be saved.',
    SettingsLoadError:
      'Settings could not be loaded. Make sure the UPC lists are provisioned (web part settings → Provision UPC lists).',

    TabRoles: 'Roles',
    RolesTitle: 'Role management',
    RolesIntro:
      'Map each app role to an Entra security group and the UI features it can see. This only controls what the app shows — actual Graph and SharePoint access always follows the directory permissions of the signed-in operator.',
    RolesGroupIdLabel: 'Entra security group ID',
    RolesGroupIdHint: 'The object ID of the security group whose members hold this role',
    RolesPermissionsLabel: 'Permissions',
    RolesSavedToast: 'Role saved.',
    RolesSaveFailed: 'The role could not be saved.',
    RolesEmptyTitle: 'No roles found',
    RolesEmptyBody: 'Make sure the UPC lists are provisioned (web part settings → Provision UPC lists).',
    PermissionCreateJobs: 'Create jobs',
    PermissionApproveJobs: 'Approve jobs',
    PermissionRunJobs: 'Run jobs',
    PermissionRetrySteps: 'Retry steps',
    PermissionSkipSteps: 'Skip steps',
    PermissionCancelJobs: 'Cancel jobs',
    PermissionManageTemplates: 'Manage templates',
    PermissionViewAudit: 'View audit log',
    PermissionManageTasks: 'Manage tasks',
    PermissionManageSettings: 'Manage settings',
    PermissionManageDelegations: 'Manage approval delegations',

    ApprovalProgressLabel: 'Approvals: {0} of {1}',
    ApprovalSatisfiedLabel: 'Approval complete',
    ApproveOnBehalfLabel: 'Approving as delegate for {0}',
    DelegationsTitle: 'Approval delegations',
    DelegationsEmptyTitle: 'No delegations set up',
    DelegationsEmptyBody: 'Delegate approval authority to cover an absence.',
    DelegationDelegatorLabel: 'Delegator (you)',
    DelegationDelegateLabel: 'Delegate',
    DelegationStartLabel: 'Start',
    DelegationEndLabel: 'End',
    DelegationReasonLabel: 'Reason',
    DelegationActiveLabel: 'Active',
    DelegationInactiveLabel: 'Inactive',
    DelegationAddLabel: 'Add delegation',
    DelegationRevokeLabel: 'Revoke',
    DelegationSavedToast: 'Delegation saved.',
    DelegationRevokedToast: 'Delegation revoked.',
    DelegationSaveFailed: 'The delegation could not be saved.',
    SettingsRequiredApprovalsLabel: 'Approvals required per job',
    SettingsRequiredApprovalsHint: 'Number of distinct approvers needed before a job can run (N-of-M quorum).',

    JobsTruncatedWarning:
      'Showing the most recent jobs. Older entries exist but are not displayed.',
    LoadMoreLabel: 'Load more',

    DashboardOverviewTitle: 'Overview',
    DashboardJobsByStatus: 'Jobs by status',
    DashboardJobsByType: 'Jobs by type',
    DashboardTotalJobs: 'Total jobs',
    DashboardSuccessRate: 'Success rate',
    DashboardTrend7Days: 'Activity (last 7 days)',
    DashboardOnboarding: 'Onboarding',
    DashboardOffboarding: 'Offboarding',
    DashboardPendingReview: 'Pending review',
    DashboardActiveNow: 'Active now',
    DashboardNeedsAttention: 'Needs attention',
    DashboardCompletedToday: 'Completed today',
    DashboardNoActivity: 'No activity in the selected period.',
    DashboardStatusLegend: 'Status breakdown',
    DashboardTypeLegend: 'Type breakdown',
    DashboardToday: 'Today',
    DashboardDays: 'days',

    AuditTitle: 'Audit trail',
    AuditEmpty: 'No audit entries yet.',
    AuditColumnTimestamp: 'Timestamp',
    AuditColumnActor: 'Actor',
    AuditColumnAction: 'Action',
    AuditColumnEndpoint: 'Graph endpoint',
    AuditColumnResponseCode: 'Response code',
    AuditColumnResult: 'Result',
    AuditResultSuccess: 'Success',
    AuditResultFailure: 'Failure',
    AuditResultSkipped: 'Skipped',

    CredentialDialogTitle: 'One-time credential hand-off',
    CredentialDialogBodyPassword: 'Temporary password for',
    CredentialDialogBodyTap: 'Temporary Access Pass for',
    CredentialDialogWarning:
      'This value is shown only once and is not stored anywhere. Copy it now and hand it over securely to the manager.',
    CopyLabel: 'Copy',
    CopiedLabel: 'Copied',
    CredentialDialogConfirm: 'I have stored it securely',
    SlowLoadTitle: 'This is taking longer than usual',
    SlowLoadBody: 'The request has not completed yet. It may be blocked, or a UPC list or column may be missing. Try again, or run Provision lists from the web part properties.',
    SchemaGapTitle: 'UPC lists are out of date',
    SchemaGapIntro: 'Some lists or columns this version needs are missing. Open the web part properties and run Provision lists to repair them.',
    SchemaGapMissingList: 'list not found',
    SchemaGapMissingColumns: 'missing columns',
    JobStalledLabel: 'Stalled',
    JobStalledTooltip: 'This job has been marked Running for longer than expected. The browser session that started it may have closed. Run it again to take over.'
  };
});
