define([], function () {
  return {
    AppTitle: 'User Provisioning Center',
    AppDescription: 'Registrera, hantera och avregistrera Microsoft 365-användare.',
    TabDashboard: 'Översikt',
    TabNewUser: 'Ny användare',
    LoadingLabel: 'Läser in',
    EmptyGenericTitle: 'Inget här ännu',
    EmptyGenericBody: 'Objekt visas här när de finns.',
    ErrorGenericTitle: 'Något gick fel',
    CorrelationIdLabel: 'Korrelations-ID',
    RetryLabel: 'Försök igen',
    RefreshLabel: 'Uppdatera',
    CloseLabel: 'Stäng',

    TabDraftBadge: 'Utkast',
    StartOverLabel: 'Börja om',
    DiscardDraftTitle: 'Ta bort utkastet?',
    DiscardDraftBody: 'All information som angetts för den här användaren tas bort.',
    DiscardDraftConfirm: 'Ta bort utkast',
    KeepEditingLabel: 'Fortsätt redigera',

    PreflightMissingTitle: 'Vissa funktioner är inte tillgängliga för dig',
    PreflightMissingIntro:
      'Ditt konto saknar Entra-roller som krävs för dessa åtgärder. Appen kan inte bevilja dem; kontakta en administratör för privilegierade roller.',
    PreflightErrorTitle: 'Behörighetskontrollen misslyckades',

    WizardTitle: 'Registrera en ny användare',
    WizardStepPersonal: 'Personuppgifter',
    WizardStepEmployment: 'Anställning',
    WizardStepIdentity: 'Identitet',
    WizardStepAccount: 'Kontoinställningar',
    WizardStepLicenses: 'Licenser',
    WizardStepAccess: 'Åtkomst',
    WizardStepReview: 'Granska och skicka',
    WizardStepDescPersonal: 'Grundläggande uppgifter om personen som börjar i organisationen.',
    WizardStepDescEmployment: 'Roll, avdelning och rapporteringsväg.',
    WizardStepDescIdentity: 'Välj inloggningsnamn. Tillgängligheten kontrolleras mot katalogen, inklusive nyligen borttagna användare.',
    WizardStepDescAccount: 'Regionala inställningar och hur inloggningsuppgifter överlämnas.',
    WizardStepDescLicenses: 'Tillgängligheten speglar era prenumerationer; kostnader hämtas från kostnadstabellen.',
    WizardStepDescAccess: 'Grupper, Teams, SharePoint-webbplatser och applikationer att tilldela, samt när åtkomsten ska granskas.',
    WizardStepDescReview: 'Inget skapas ännu — begäran skickas för godkännande.',

    AccessSecurityGroupsLabel: 'Säkerhetsgrupper',
    AccessSecurityGroupsHint: 'Sök Entra-säkerhetsgrupper efter namn.',
    AccessM365GroupsLabel: 'Microsoft 365-grupper',
    AccessM365GroupsHint: 'Sök Entra Microsoft 365-grupper efter namn.',
    AccessTeamsLabel: 'Teams',
    AccessTeamsHint: 'Sök i den kurerade Teams-katalogen efter namn.',
    AccessSitesLabel: 'SharePoint-webbplatser',
    AccessSitesHint: 'Sök i den kurerade webbplatskatalogen efter namn.',
    AccessApplicationsLabel: 'Applikationer',
    AccessApplicationsHint: 'Sök i den kurerade applikationskatalogen efter namn.',
    AccessGroupSearchPlaceholder: 'Sök efter namn…',
    AccessGroupSearchHint: 'Skriv minst 2 tecken för att söka.',
    AccessGroupSearchNoMatches: 'Inga grupper hittades.',
    AccessCatalogNoMatches: 'Inga träffar.',
    AccessRoleMember: 'Medlem',
    AccessRoleOwner: 'Ägare',
    AccessRoleVisitor: 'Besökare',
    AccessExpirationLabel: 'Granska åtkomst efter (dagar)',
    AccessExpirationHint:
      'Lämna som 0 för ingen schemalagd granskning. En serviceskrivbordsuppgift skapas för att granska kontots åtkomst efter så här många dagar — inget sker automatiskt.',
    AccessNoCatalogItems: 'Inget konfigurerat. Be en administratör lägga till poster i katalogen.',
    AccessExpirationNone: 'Ingen granskning schemalagd',
    ApproverGroupIdLabel: 'Godkännargrupp (valfritt)',
    ApproverGroupIdHint:
      'Objekt-ID för Entra-säkerhetsgrupp. När det anges kan endast medlemmar i denna grupp godkänna jobb som skapats från denna mall — lämna tomt för ingen ytterligare begränsning.',
    ApprovalRestrictedMessage: 'Detta jobb kan endast godkännas av en medlem i den grupp som mallen kräver.',
    ApprovalRestrictedNotMember: 'Du är inte medlem i den grupp som krävs och kan därför inte godkänna detta jobb.',

    IdentityAccountTypeLabel: 'Kontotyp',
    IdentityAccountTypeMember: 'Anställd eller konsult (skapar ett konto)',
    IdentityAccountTypeGuest: 'Extern gäst (skickar en inbjudan)',
    IdentityGuestEmailLabel: 'Gästens e-postadress',
    IdentityGuestIntro: 'Entra skickar en inbjudan till denna adress — det finns inget lösenord eller inloggningsnamn att välja.',
    CloneFromLabel: 'Kopiera åtkomst från (valfritt)',
    CloneFromHint: 'Kopierar denna persons licenser och kvalificerade gruppmedlemskap till den nyanställda, utöver det som väljs nedan.',
    WizardStepsAriaLabel: 'Guidens steg',
    WizardStepCompletedAria: 'slutfört',
    WizardStepOfLabel: 'Steg {0} av {1}',
    BackLabel: 'Tillbaka',
    NextLabel: 'Nästa',
    SubmitLabel: 'Skicka för godkännande',
    SubmitNoApprovalLabel: 'Skapa jobb',
    SubmittingLabel: 'Skickar…',
    SubmitSuccess: 'Begäran har skickats och väntar på godkännande.',
    SubmitSuccessNoApproval: 'Provisioneringsjobbet har skapats och är klart att köras.',
    SubmitFailure: 'Begäran kunde inte skickas.',
    WizardStepDescReviewNoApproval:
      'Inget skapas ännu — när du skickar skapas ett jobb som är klart att köras.',
    ReviewIntroNoApproval:
      'Granska begäran. När den skickas skapas ett provisioneringsjobb som kan köras från översikten.',
    OffboardStepDescReviewNoApproval:
      'Inget utförs ännu — när du skickar skapas ett jobb som är klart att köras.',
    OffboardSubmitSuccessNoApproval: 'Avregistreringsjobbet har skapats och är klart att köras.',
    BulkIntroNoApproval:
      'Ladda upp en CSV-fil för att skapa flera registreringsjobb samtidigt. Varje rad blir ett eget jobb, klart att köras från översikten.',

    FirstNameLabel: 'Förnamn',
    LastNameLabel: 'Efternamn',
    DisplayNameLabel: 'Visningsnamn',
    EmployeeIdLabel: 'Anställnings-ID',
    MobilePhoneLabel: 'Mobiltelefon',
    PersonalEmailLabel: 'Privat e-post',
    PhotoLabel: 'Foto',
    PhotoHint: 'Valfritt. Ändras storlek och komprimeras automatiskt — stora foton krymps för att passa.',
    ChoosePhotoLabel: 'Välj foto',
    ChangePhotoLabel: 'Byt foto',
    RemovePhotoLabel: 'Ta bort foto',
    PhotoUploadError: 'Den bilden kunde inte användas — prova en mindre eller enklare bild.',
    JobTitleLabel: 'Befattning',
    DepartmentLabel: 'Avdelning',
    CompanyLabel: 'Företag',
    OfficeLabel: 'Kontor',
    CountryLabel: 'Land',
    CountryHint: 'Det fysiska kontorslandet. Skiljer sig från användningsplats, som styr licensberättigande.',
    ManagerLabel: 'Chef',
    ManagerSearchPlaceholder: 'Sök på namn eller e-post',
    EmployeeTypeLabel: 'Anställningstyp',
    EmployeeTypeEmployee: 'Anställd',
    EmployeeTypeContractor: 'Konsult',
    HireDateLabel: 'Startdatum',
    DomainLabel: 'Domän',
    UpnLabel: 'Användarnamn (UPN)',
    MailNicknameLabel: 'E-postalias',
    UsageLocationLabel: 'Användningsplats',
    AccountEnabledLabel: 'Kontot aktivt vid skapande',
    CredentialModeLabel: 'Inloggningsuppgift vid första inloggning',
    CredentialModePassword: 'Tillfälligt lösenord',
    CredentialModeTap: 'Tillfällig åtkomstkod (TAP)',
    ForceChangePasswordLabel: 'Kräv lösenordsbyte vid första inloggningen',

    ValidationRequired: 'Fältet är obligatoriskt.',
    ValidationTooLong: 'Värdet är för långt.',
    ValidationInvalidEmail: 'Ange en giltig e-postadress.',
    ValidationInvalidPhone: 'Ange ett giltigt telefonnummer.',
    ValidationInvalidDate: 'Ange ett giltigt datum.',
    ValidationInvalidCountry: 'Välj ett land.',
    ValidationInvalidChoice: 'Välj ett giltigt alternativ.',
    ValidationInvalidUpn: 'Ange ett giltigt användarnamn.',
    ValidationInvalidLocalPart: 'Endast a-z, 0-9, punkt och bindestreck; ingen inledande eller avslutande punkt.',
    EmployeeIdDuplicate: 'Detta anställnings-ID finns redan i katalogen.',
    EmployeeIdChecking: 'Kontrollerar anställnings-ID…',

    IdentityCandidatesLabel: 'Tillgängliga inloggningsnamn',
    IdentityRecommended: 'Rekommenderas',
    IdentityAlternatives: 'Alternativ',
    IdentityRejectedTitle: 'Inte tillgängligt',
    IdentityReasonReserved: 'reserverat namn',
    IdentityReasonCollision: 'används redan',
    IdentityReasonCollisionDeleted: 'används av en nyligen borttagen användare',
    IdentityNoCandidate: 'Inget tillgängligt namn kunde genereras. Justera namnfälten.',
    IdentityResolving: 'Kontrollerar namntillgänglighet…',
    IdentityNeedsNames: 'Ange för- och efternamn i steg 1 för att generera inloggningsnamn.',

    LicenseColumnProduct: 'Produkt',
    LicenseColumnAvailable: 'Tillgängliga',
    LicenseColumnCost: 'Kostnad / månad',
    LicenseExhausted: 'Inga enheter kvar',
    LicenseNoCost: '—',
    LicenseTotalPerMonth: 'Valda licenser per månad',

    ReviewIntro: 'Granska begäran. När den skickas skapas ett jobb som kräver godkännande innan något utförs.',
    ReviewNoLicenses: 'Inga licenser valda',
    ReviewNoManager: 'Ingen chef vald',
    ReviewNoCountry: 'Inte angivet',
    ReviewApproverGroupDefault: 'Standardgodkännande (ingen mallbegränsning)',
    ReviewPhotoAttached: 'Bifogat',
    ReviewPhotoNone: 'Inget',
    ReviewEditLabel: 'Redigera',
    ReviewEditSectionAria: 'Redigera {0}',
    ReviewValidationTitle: 'Viss information saknas eller är ogiltig',

    JobsTitle: 'Provisioneringsjobb',
    JobsEmptyTitle: 'Inga provisioneringsjobb',
    JobsEmptyBody: 'Skickade onboarding-begäranden visas här.',
    JobsEmptyCta: 'Skapa din första användare',
    JobColumnJob: 'Jobb',
    JobColumnCreated: 'Skapad',
    JobColumnActions: 'Åtgärder',
    ApprovedByLabel: 'Godkänd av',
    JobColumnType: 'Typ',
    JobColumnTarget: 'Målanvändare',
    JobColumnStatus: 'Status',
    JobColumnRequestedBy: 'Begärd av',
    JobDetailTitle: 'Jobbdetaljer',
    JobStepsTitle: 'Steg',
    ApproveLabel: 'Godkänn',
    RunLabel: 'Kör nu',
    ResumeLabel: 'Återuppta',
    RetryStepLabel: 'Försök igen',
    SkipStepLabel: 'Hoppa över steg',
    CancelJobLabel: 'Avbryt jobb',
    CancelJobDialogTitle: 'Avbryta jobbet?',
    CancelJobDialogBody:
      'Steg som redan har slutförts återställs inte. Detta kan inte ångras.',
    KeepJobLabel: 'Behåll jobb',
    RegenerateCredentialsLabel: 'Generera nya inloggningsuppgifter',
    JobRunningLabel: 'Kör…',
    JobAttemptsLabel: 'försök',
    JobStatusAnnouncement: 'Jobbstatus: {0}',
    JobApprovedToast: 'Jobbet har godkänts.',
    JobCancelledToast: 'Jobbet har avbrutits.',
    JobActionFailed: 'Åtgärden misslyckades.',
    JobProgressLabel: 'Steg {0} av {1}',
    JobDoNotClose: 'Provisionering pågår — håll den här fliken öppen. Om du stänger den pausas jobbet; det återupptas när du öppnar panelen igen.',
    JobCompletedOf: 'Klart {0} av {1} steg',
    JobElapsedLabel: 'Förfluten tid',
    JobStepStarting: 'Startar…',

    StatusDraft: 'Utkast',
    StatusPendingApproval: 'Väntar på godkännande',
    StatusApproved: 'Godkänt',
    StatusScheduled: 'Schemalagt',
    StatusRunning: 'Körs',
    StatusPartiallyFailed: 'Delvis misslyckat',
    StatusFailed: 'Misslyckat',
    StatusCompleted: 'Slutfört',
    StatusCancelled: 'Avbrutet',
    StepStatusPending: 'Väntar',
    StepStatusRunning: 'Körs',
    StepStatusCompleted: 'Slutfört',
    StepStatusFailed: 'Misslyckat',
    StepStatusSkipped: 'Överhoppat',

    StepValidateInput: 'Validera indata',
    StepCreateUser: 'Skapa användare',
    StepSetUsageLocation: 'Ange användningsplats',
    StepAssignManager: 'Tilldela chef',
    StepAssignLicenses: 'Tilldela licenser',
    StepPresentCredentials: 'Överlämna inloggningsuppgifter',
    StepFinalizeAudit: 'Slutför granskningslogg',

    JobTypeOnboard: 'Registrering',
    JobTypeOffboard: 'Avregistrering',
    JobTypeTransfer: 'Överflyttning',
    JobTypeClone: 'Kloning',
    JobTypeBulk: 'Massimport',

    KpiFailed7: 'Misslyckade (7 dagar)',
    KpiCompleted7: 'Slutförda (7 dagar)',
    SearchJobsPlaceholder: 'Sök på användare eller beställare',
    FilterTypeAll: 'Alla typer',
    JobsNoMatches: 'Inga jobb matchar de aktuella filtren.',

    TabTemplates: 'Mallar',
    TemplatesTitle: 'Provisioneringsmallar',
    TemplatesEmptyTitle: 'Inga mallar ännu',
    TemplatesEmptyBody: 'Mallar förifyller registreringsguiden med avdelningens standardval.',
    NewTemplateLabel: 'Ny mall',
    TemplateNameLabel: 'Mallnamn',
    TemplateColumnName: 'Namn',
    TemplateColumnActive: 'Aktiv',
    TemplateColumnVersion: 'Version',
    TemplateInactiveLabel: 'Inaktiv',
    TemplateActiveLabel: 'Aktiv (valbar i guiden)',
    TemplateSavedToast: 'Mallen har sparats.',
    TemplateEditTitle: 'Redigera mall',
    SaveLabel: 'Spara',
    CancelLabel: 'Avbryt',
    StartFromTemplateLabel: 'Utgå från mall',
    StartFromBlank: 'Tom',
    TemplateAppliedToast: 'Mall tillämpad: {0}',

    TabOffboard: 'Avregistrera användare',
    OffboardTitle: 'Avregistrera en användare',
    OffboardStepTarget: 'Välj användare',
    OffboardStepAccess: 'Åtkomst tas bort',
    OffboardStepTiming: 'Tidpunkt',
    OffboardStepDescTarget: 'Sök i katalogen efter personen som lämnar organisationen.',
    OffboardStepDescAccess:
      'Välj vad som tas bort. Inloggning blockeras alltid och sessioner återkallas.',
    OffboardStepDescTiming: 'Kör direkt efter godkännande eller på ett valt datum.',
    OffboardStepDescReview: 'Inget utförs ännu — begäran skickas för godkännande.',
    OffboardUserLabel: 'Användare',
    OffboardAlwaysBlock:
      'Inloggning blockeras och alla aktiva sessioner återkallas som första steg i varje avregistrering.',
    OffboardRemoveLicensesLabel: 'Ta bort tilldelade licenser',
    OffboardRemoveGroupsLabel: 'Ta bort gruppmedlemskap',
    OffboardMailboxLabel: 'Brevlåda',
    OffboardMailboxNone: 'Lämna oförändrad',
    OffboardMailboxShared: 'Konvertera till delad brevlåda (uppgift till servicedesk)',
    OffboardMailboxForward: 'Vidarebefordra e-post (uppgift till servicedesk)',
    OffboardForwardAddressLabel: 'Adress för vidarebefordran',
    OffboardOneDriveLabel: 'Ge OneDrive-åtkomst till (valfritt)',
    OffboardTimingImmediate: 'Så snart jobbet är godkänt och körs',
    OffboardTimingScheduled: 'På ett datum',
    OffboardDateLabel: 'Datum',
    OffboardSubmitSuccess: 'Begäran om avregistrering har skickats och väntar på godkännande.',
    ScheduledForLabel: 'Schemalagt till',
    YesLabel: 'Ja',
    NoLabel: 'Nej',
    StepValidateTarget: 'Validera målanvändare',
    StepBlockSignIn: 'Blockera inloggning & återkalla sessioner',
    StepRemoveLicenses: 'Ta bort licenser',
    StepRemoveGroups: 'Ta bort gruppmedlemskap',
    StepCreateHandoverTasks: 'Skapa överlämningsuppgifter',

    TabTransfer: 'Överflyttning',
    TransferTitle: 'Flytta användare',
    TransferIntro:
      'Ändra avdelning, jobbtitel, kontor, chef eller licenser för en befintlig användare. Lämna ett fält tomt för att lämna det oförändrat.',
    TransferUserLabel: 'Användare att flytta',
    TransferLeaveBlankHint: 'Lämna tomt för ingen ändring',
    TransferAddLicensesLabel: 'Lägg till licenser',
    TransferRemoveLicensesLabel: 'Ta bort licenser',
    TransferNoCurrentLicenses: 'Denna användare har inga tilldelade licenser.',

    TabBulk: 'Massimport',
    BulkTitle: 'Massimport av användare',
    BulkIntro:
      'Ladda upp en CSV-fil för att skapa flera registreringsbegäranden samtidigt. Varje rad blir ett eget jobb i godkännandeflödet.',
    BulkDownloadTemplate: 'Ladda ned CSV-mall',
    BulkChooseFile: 'Välj CSV-fil',
    BulkValidateLabel: 'Validera rader',
    BulkValidatingLabel: 'Validerar rad {0} av {1}…',
    BulkReadySummary: '{0} av {1} rader är klara.',
    BulkSubmitLabel: 'Skapa {0} jobb',
    BulkSubmittedToast: '{0} registreringsbegäranden har skapats.',
    BulkTooManyRows: 'Högst {0} rader kan importeras åt gången.',
    BulkNoDataRows: 'Filen saknar datarader.',
    BulkMissingColumns: 'Obligatoriska kolumner saknas: {0}',
    BulkColumnRow: 'Rad',
    BulkColumnProblems: 'Problem',
    BulkRowReady: 'Klar',
    BulkRowError: 'Fel',
    BulkErrDuplicateInFile: 'Dubblett av anställnings-ID i filen',
    BulkErrUnknownLicense: 'Okänd licens: {0}',
    BulkErrUnknownDomain: 'Domänen är inte verifierad i klientorganisationen',
    BulkErrNoUpn: 'Inget tillgängligt inloggningsnamn kunde genereras',
    BulkErrDuplicateUpn: 'Inloggningsnamnet krockar med en annan rad',
    BulkErrUnknownTemplate: 'Okänd mall: {0}',

    TabBulkOffboard: 'Massavregistrering',
    BulkOffboardTitle: 'Massavregistrering av användare',
    BulkOffboardIntro:
      'Ladda upp en CSV-fil för att skapa flera avregistreringsbegäranden samtidigt. Varje rad blir ett eget jobb i godkännandeflödet.',
    BulkOffboardIntroNoApproval:
      'Ladda upp en CSV-fil för att skapa flera avregistreringsbegäranden samtidigt. Varje rad blir ett eget jobb, klart att köras.',
    BulkOffboardSubmitLabel: 'Skapa {0} jobb',
    BulkOffboardSubmittedToast: '{0} avregistreringsbegäranden har skapats.',
    BulkErrInvalidMailboxAction: 'Okänt mailboxAction-värde: {0} (använd none, convertShared eller forward)',
    BulkErrUserNotFound: 'Ingen användare med detta inloggningsnamn hittades i katalogen',
    OffboardForwardingRequired: 'En vidarebefordringsadress krävs när mailboxAction är forward',

    TabTasks: 'Uppgifter',
    TasksTitle: 'Servicedesk-uppgifter',
    TasksEmptyTitle: 'Inga öppna uppgifter',
    TasksEmptyBody: 'Överlämningsarbete som inte kan automatiseras hamnar här.',
    ShowCompletedLabel: 'Visa slutförda',
    MarkDoneLabel: 'Markera som klar',
    TaskCompletedToast: 'Uppgiften har slutförts.',
    TaskStatusOpen: 'Öppen',
    TaskStatusDone: 'Klar',
    TaskCompletedByLabel: 'Slutförd av',
    TasksColumnTitle: 'Titel',
    TasksColumnType: 'Typ',
    TasksColumnInstructions: 'Instruktioner',
    TasksColumnAssignedTo: 'Tilldelad till',
    ExportCsvLabel: 'Exportera CSV',
    TaskTypeMailboxConvertShared: 'Konvertera brevlåda till delad',
    TaskTypeMailboxDelegation: 'Brevlådedelegering',
    TaskTypeMailForwarding: 'Vidarebefordran av e-post',
    TaskTypeHideFromGal: 'Dölj från adresslistan',
    TaskTypeDistributionList: 'Distributionslistor',
    TaskTypeLitigationHold: 'Litigation hold',
    TaskTypeOneDriveHandling: 'OneDrive-hantering',
    TaskTypeAutoReply: 'Autosvar',
    TaskTypeHardware: 'Hårdvara',
    TaskTypeThirdPartyApp: 'Tredjepartsapp',
    TaskTypeOnPremAdAccount: 'Åtgärd i lokalt AD-konto',
    TaskTypeGroupAssignment: 'Grupptilldelning',
    TaskTypeTeamAssignment: 'Teams-tilldelning',
    TaskTypeSharePointAccess: 'SharePoint-webbplatsåtkomst',
    TaskTypeApplicationAssignment: 'Apptilldelning',
    TaskTypeAccessReview: 'Åtkomstgranskning',
    TaskTypeOther: 'Övrigt',

    TabSettings: 'Inställningar',
    SettingsTitle: 'Inställningar',
    SettingsIntro:
      'Inställningarna lagras på den här webbplatsen och gäller alla som använder provisioneringscentret.',
    SettingsRequireApprovalLabel: 'Kräv godkännande innan jobb kan köras',
    SettingsRequireApprovalHint:
      'Av: nya begäranden skapas klara att köras. Jobb som redan väntar på godkännande behåller sitt läge.',
    SettingsBulkLimitLabel: 'Radgräns för massimport',
    SettingsRefreshLabel: 'Uppdateringsintervall för översikten (sekunder)',
    SettingsSavedToast: 'Inställningarna har sparats.',
    SettingsSaveFailed: 'Inställningarna kunde inte sparas.',
    SettingsLoadError:
      'Inställningarna kunde inte läsas. Kontrollera att UPC-listorna är provisionerade (webbdelens inställningar → Provisionera UPC-listor).',

    TabRoles: 'Roller',
    RolesTitle: 'Rollhantering',
    RolesIntro:
      'Koppla varje approll till en Entra-säkerhetsgrupp och de funktioner i gränssnittet den ska kunna se. Detta styr endast vad appen visar — faktisk åtkomst till Graph och SharePoint följer alltid den inloggade operatörens egna katalogbehörigheter.',
    RolesGroupIdLabel: 'Entra-säkerhetsgruppens ID',
    RolesGroupIdHint: 'Objekt-ID för säkerhetsgruppen vars medlemmar innehar denna roll',
    RolesPermissionsLabel: 'Behörigheter',
    RolesSavedToast: 'Rollen har sparats.',
    RolesSaveFailed: 'Rollen kunde inte sparas.',
    RolesEmptyTitle: 'Inga roller hittades',
    RolesEmptyBody: 'Kontrollera att UPC-listorna är provisionerade (webbdelens inställningar → Provisionera UPC-listor).',
    PermissionCreateJobs: 'Skapa jobb',
    PermissionApproveJobs: 'Godkänna jobb',
    PermissionRunJobs: 'Köra jobb',
    PermissionRetrySteps: 'Försöka igen med steg',
    PermissionSkipSteps: 'Hoppa över steg',
    PermissionCancelJobs: 'Avbryta jobb',
    PermissionManageTemplates: 'Hantera mallar',
    PermissionViewAudit: 'Visa granskningslogg',
    PermissionManageTasks: 'Hantera uppgifter',
    PermissionManageSettings: 'Hantera inställningar',
    PermissionManageDelegations: 'Hantera godkännandedelegeringar',

    ApprovalProgressLabel: 'Godkännanden: {0} av {1}',
    ApprovalSatisfiedLabel: 'Godkännande klart',
    ApproveOnBehalfLabel: 'Godkänner som delegat för {0}',
    DelegationsTitle: 'Godkännandedelegeringar',
    DelegationsEmptyTitle: 'Inga delegeringar konfigurerade',
    DelegationsEmptyBody: 'Delegera godkännanderätt för att täcka en frånvaro.',
    DelegationDelegatorLabel: 'Delegerar (du)',
    DelegationDelegateLabel: 'Delegat',
    DelegationStartLabel: 'Start',
    DelegationEndLabel: 'Slut',
    DelegationReasonLabel: 'Anledning',
    DelegationActiveLabel: 'Aktiv',
    DelegationInactiveLabel: 'Inaktiv',
    DelegationAddLabel: 'Lägg till delegering',
    DelegationRevokeLabel: 'Återkalla',
    DelegationSavedToast: 'Delegeringen har sparats.',
    DelegationRevokedToast: 'Delegeringen har återkallats.',
    DelegationSaveFailed: 'Delegeringen kunde inte sparas.',
    SettingsRequiredApprovalsLabel: 'Godkännanden som krävs per jobb',
    SettingsRequiredApprovalsHint: 'Antal unika godkännare som krävs innan ett jobb kan köras (N-av-M-kvorum).',

    JobsTruncatedWarning:
      'Visar de senaste jobben. Äldre poster finns men visas inte.',
    LoadMoreLabel: 'Läs in fler',

    DashboardOverviewTitle: 'Översikt',
    DashboardJobsByStatus: 'Jobb per status',
    DashboardJobsByType: 'Jobb per typ',
    DashboardTotalJobs: 'Totalt antal jobb',
    DashboardSuccessRate: 'Framgångsgrad',
    DashboardTrend7Days: 'Aktivitet (senaste 7 dagarna)',
    DashboardOnboarding: 'Onboarding',
    DashboardOffboarding: 'Offboarding',
    DashboardPendingReview: 'Väntar på granskning',
    DashboardActiveNow: 'Aktiva nu',
    DashboardNeedsAttention: 'Kräver åtgärd',
    DashboardCompletedToday: 'Slutförda idag',
    DashboardNoActivity: 'Ingen aktivitet under vald period.',
    DashboardStatusLegend: 'Statusfördelning',
    DashboardTypeLegend: 'Typfördelning',
    DashboardToday: 'Idag',
    DashboardDays: 'dagar',

    AuditTitle: 'Granskningslogg',
    AuditEmpty: 'Inga loggposter ännu.',
    AuditColumnTimestamp: 'Tidsstämpel',
    AuditColumnActor: 'Utförd av',
    AuditColumnAction: 'Åtgärd',
    AuditColumnEndpoint: 'Graph-slutpunkt',
    AuditColumnResponseCode: 'Svarskod',
    AuditColumnResult: 'Resultat',
    AuditResultSuccess: 'Lyckades',
    AuditResultFailure: 'Misslyckades',
    AuditResultSkipped: 'Överhoppad',

    CredentialDialogTitle: 'Engångsöverlämning av inloggningsuppgift',
    CredentialDialogBodyPassword: 'Tillfälligt lösenord för',
    CredentialDialogBodyTap: 'Tillfällig åtkomstkod för',
    CredentialDialogWarning:
      'Värdet visas bara en gång och lagras ingenstans. Kopiera det nu och överlämna det säkert till chefen.',
    CopyLabel: 'Kopiera',
    CopiedLabel: 'Kopierat',
    CredentialDialogConfirm: 'Jag har sparat den säkert'
  };
});
